### PR TITLE
Create the Initial Chrony charm

### PR DESCRIPTION
**Pull request by weiiwang01**
This pull request introduces the initial version of the Chrony charm, which provides basic NTP server functionality (synchronize with other NTP servers and serve as an NTP server itself).

Included in this pull request:
- Implementation of the basic Chrony charm
- Unit tests
- Integration tests

### CODE REVIEW

**Review by mthaddon — COMMENTED** [review]
A few minor comments. Also, can you tag the PR with the appropriate tags, and include the checklist as we do for other projects (will likely need to update the issue template if that hasn't already been done)?

**Review by yanksyoon — DISMISSED** [review]
Very cool! Very minor nitpicks, please feel free to resolve :)

**Review by yanksyoon — DISMISSED** [review]
LGTM, just minor nitpicks!

**Review by cbartz — COMMENTED** [review]
Looks good, have a few comments. Could you please add the complexity label of the PR (I assume complex) and fill out the pull request template? Thank you.

**Review by cbartz — APPROVED** [review]
LGTM

**Review by yanksyoon — APPROVED** [review]
LGTM!

**Pull request merged**
